CREATE TABLE subscribers (
    id BIGINT PRIMARY KEY,
    msisdn VARCHAR(15)
);

CREATE TABLE cdr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_type VARCHAR(2),
    from_msisdn VARCHAR(15),
    to_msisdn VARCHAR(15),
    call_start TIMESTAMP,
    call_end TIMESTAMP
);